networks:
  k6:
  grafana:

services:

  timescaledb:
    image: timescale/timescaledb:2.22.0-pg16
    restart: unless-stopped
    networks:
      - grafana
      - k6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    restart: unless-stopped
    image: grafana/grafana:12.2
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana_dashboards
      - grafana_lib:/var/lib/grafana
      #- grafana_etc:/etc/grafana
      - grafana_logs:/var/log/grafana
      - ./grafana_config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana_config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml      

  k6:
    build: ./docker
    platform: linux/amd64
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=timescaledb=postgresql://postgres:postgres@timescaledb:5432/metrics
    volumes:
      - ./scripts:/scripts


volumes:
  postgres_data:
  grafana_etc:
  grafana_lib:
  grafana_logs: